[package]
name = "private_voting_test"
type = "lib"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v4.3.1", directory="aztec" }
private_voting_contract = { path = "../aztec-private-voting_contract" }
