[package]
name = "private_voting_contract"
type = "contract"

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-nr", tag="v5.0.0", directory="aztec" }
balance_set = { git="https://github.com/AztecProtocol/aztec-nr", tag="v5.0.0", directory="balance-set" }
